services:
  postgres:
    image: bitnami/postgresql:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=tamojunto
    volumes:
      - db_data:/bitnami/postgresql
    restart: unless-stopped
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # porta AMQP (sua aplicação conecta aqui)
      - "15672:15672" # porta do painel web (Management UI)
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=secret
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  rabbitmq_data:

networks:
  my_network:
    driver: bridge